# Generated by Django 4.0 on 2022-03-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_portfolio_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tarigi',
            field=models.DateField(auto_now=True),
        ),
    ]
