# Generated by Django 4.0 on 2022-03-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_portfolio_date_portfolio_tarigi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='tarigi',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
