# Generated by Django 4.0 on 2022-03-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_languageskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('procent', models.CharField(max_length=30)),
            ],
        ),
    ]
