# Generated by Django 4.0 on 2022-03-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_codingskills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codingskills',
            options={'verbose_name': 'CodingSkills', 'verbose_name_plural': 'Coding Skills'},
        ),
        migrations.AlterModelOptions(
            name='languageskills',
            options={'verbose_name': 'LanguageSkills', 'verbose_name_plural': 'Language Skills'},
        ),
        migrations.AlterField(
            model_name='workexperiencecard',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
